# Generated by Django 3.0.5 on 2020-05-27 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name']},
        ),
    ]
