# Generated by Django 3.0.5 on 2020-05-16 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('appt_location', models.TextField(max_length=100)),
                ('reason', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=256)),
                ('appts', models.ManyToManyField(through='drview.Appointments', to='patientview.Patient')),
                ('specialties', models.ManyToManyField(blank=True, related_name='specialty_of', to='drview.Specialty')),
                ('treats', models.ManyToManyField(blank=True, related_name='treated_by', to='patientview.Patient')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.AddField(
            model_name='appointments',
            name='appt_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drview.Doctor'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='appt_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientview.Patient'),
        ),
    ]
