# Generated by Django 3.0.5 on 2020-05-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appt_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='reason',
            field=models.TextField(max_length=64),
        ),
    ]
