# Generated by Django 3.0.5 on 2020-05-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drview', '0002_auto_20200518_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='byweekday',
            field=models.CharField(choices=[('RRUle.MO', 'Mon'), ('RRule.TU', 'Tues'), ('RRule.WE', 'Wed'), ('RRule.TH', 'Thurs'), ('RRule.FR', 'Fri')], default='', max_length=64),
        ),
        migrations.AddField(
            model_name='appointments',
            name='repetition',
            field=models.CharField(choices=[('RRule.DAILY', 'Daily'), ('RRULE.WEEKLY', 'Weekly'), ('RRULE.MONTHLY', 'Monthly')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='reason',
            field=models.TextField(max_length=256),
        ),
    ]
