# Generated by Django 3.0.5 on 2020-05-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drview', '0003_auto_20200528_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='byweekday',
            field=models.CharField(choices=[('RRule.MO', 'Mon'), ('RRule.TU', 'Tues'), ('RRule.WE', 'Wed'), ('RRule.TH', 'Thurs'), ('RRule.FR', 'Fri')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='repetition',
            field=models.CharField(choices=[('RRule.DAILY', 'Daily'), ('RRule.WEEKLY', 'Weekly'), ('RRule.MONTHLY', 'Monthly')], max_length=20),
        ),
    ]
